# Generated by Django 4.0.1 on 2022-02-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('JobTitile', models.CharField(max_length=100)),
                ('Amount', models.FloatField()),
                ('Location', models.CharField(max_length=1000)),
                ('Salary', models.FloatField()),
                ('Description', models.TextField()),
                ('ApplicationLink', models.CharField(max_length=100)),
                ('CompanyName', models.CharField(max_length=100)),
                ('CompanyWebsite', models.CharField(max_length=100)),
            ],
        ),
    ]
