# Generated by Django 4.0.1 on 2022-02-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miningCareers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='Amount',
        ),
    ]
