# Generated by Django 4.0.1 on 2022-02-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miningCareers', '0002_remove_job_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titile', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
    ]
