# Generated by Django 4.0.1 on 2022-02-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miningCareers', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='Level',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='Status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='Type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
