# Generated by Django 4.0.1 on 2022-02-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miningCareers', '0004_job_department_job_level_job_status_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='Level',
            field=models.IntegerField(default=0),
        ),
    ]
