# Generated by Django 4.0.1 on 2022-02-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miningCareers', '0005_blog_image_alter_job_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancle', 'Cancle')], default='Pending', max_length=100),
        ),
    ]
