# Generated by Django 4.0.1 on 2022-02-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miningCareers', '0007_job_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='job',
            name='Level',
        ),
        migrations.AddField(
            model_name='job',
            name='isfeatured',
            field=models.BooleanField(default=False),
        ),
    ]
