# Generated by Django 4.0.1 on 2022-02-14 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miningCareers', '0008_remove_job_department_remove_job_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='isfeatured',
            new_name='Is_Featured',
        ),
    ]
